package com.finance.business.errors

trait BusinessError

case object UserDoesNotExistError extends BusinessError

case object SourceDoesNotExistError extends BusinessError

case object SourceAlreadyExistsError extends BusinessError

case object AccountDoesNotExistError extends BusinessError

case object AccountAlreadyExistsError extends BusinessError

case object TransactionDoesNotExistError extends BusinessError

case object TransactionAlreadyExistsError extends BusinessError

case object ReferencedByTransactionError extends BusinessError

case object NameMustBeDefinedError extends BusinessError

case object DescriptionMustBeDefinedError extends BusinessError

case object NameExceedsMaxLengthError extends BusinessError

case object DescriptionExceedsMaxLengthError extends BusinessError

case object ParentCategoryDoesNotExistError extends BusinessError

case object ParentCategoryCannotBeLeaf extends BusinessError

case object CategoryEffectiveTimeOutsideParent extends BusinessError

case object CategoryDoesNotExistError extends BusinessError

case object CategoryAlreadyExistsError extends BusinessError

