openapi: "3.0.0"
info:
  title: "finance api"
  version: "0.0.1"
paths:
  /category:
    $ref: "paths/category.yaml#/CreateGetCategory"
  /category/{id}:
    $ref: "paths/category.yaml#/UpdateDeleteCategory"
  /category/amountinrange:
    $ref: "paths/category.yaml#/GetAmountSpentInRange"
  /transaction:
    $ref: "paths/transaction.yaml#/CreateTransaction"
  /transaction/{id}:
    $ref: "paths/transaction.yaml#/UpdateDeleteTransaction"
  /source:
    $ref: "paths/source.yaml#/CreateGetSource"
  /source/{id}:
    $ref: "paths/source.yaml#/UpdateDeleteSource"
  /account:
    $ref: "paths/account.yaml#/CreateGetAccount"
  /account/{id}:
    $ref: "paths/account.yaml#/UpdateDeleteAccount"
  /asset:
    $ref: "paths/asset.yaml#/CreateAsset"
  /asset/{id}:
    $ref: "paths/asset.yaml#/UpdateDeleteAsset"
  /asset/stockvalue:
    $ref: "paths/asset.yaml#/GetStockValue"
  /reporting/accountvalue:
    $ref: "paths/reporting.yaml#/GetAccountValue"
  /reporting/networth:
    $ref: "paths/reporting.yaml#/GetNetWorth"
  /timeperiod:
    $ref: "paths/timeperiod.yaml#/GetTimePeriod"
  /transfer:
    $ref: "paths/transfer.yaml#/CreateTransfer"
  /transfer/{id}:
    $ref: "paths/transfer.yaml#/UpdateDeleteTransfer"
  /record:
    $ref: "paths/record.yaml#/GetRecord"
  /payback:
    $ref: "paths/payback.yaml#/CreatePayback"
  /payback/{id}:
    $ref: "paths/payback.yaml#/UpdateDeletePayback"
  /payback/balance:
    $ref: "paths/payback.yaml#/GetPaybackBalance"
  /payback/balancesummary:
    $ref: "paths/payback.yaml#/GetPaybackBalanceSummary"
components:
  schemas:
    Category:
      $ref: "schemas/category.yaml#/Category"
    Budget:
      $ref: "schemas/category.yaml#/Budget"
    AmountSpentInRangeQuery:
      $ref: "schemas/category.yaml#/AmountSpentInRangeQuery"
    AmountSpentInRange:
      $ref: "schemas/category.yaml#/AmountSpentInRange"
    CategoryAmountSpent:
      $ref: "schemas/category.yaml#/CategoryAmountSpent"
    BudgetAmountSpent:
      $ref: "schemas/category.yaml#/BudgetAmountSpent"
    Transaction:
      $ref: "schemas/transaction.yaml#/Transaction"
    Amount:
      $ref: "schemas/transaction.yaml#/Amount"
    Source:
      $ref: "schemas/source.yaml#/Source"
    SourceQuery:
      $ref: "schemas/source.yaml#/SourceQuery"
    Account:
      $ref: "schemas/account.yaml#/Account"
    Asset:
      $ref: "schemas/asset.yaml#/Asset"
    Stock:
      $ref: "schemas/asset.yaml#/Stock"
    StockAction:
      $ref: "schemas/asset.yaml#/StockAction"
    StockValue:
      $ref: "schemas/asset.yaml#/StockValue"
    AccountValue:
      $ref: "schemas/reporting.yaml#/AccountValue"
    AccountValueQuery:
      $ref: "schemas/reporting.yaml#/AccountValueQuery"
    TimePeriod:
      $ref: "schemas/timeperiod.yaml#/TimePeriod"
    TimePeriodQuery:
      $ref: "schemas/timeperiod.yaml#/TimePeriodQuery"
    Transfer:
      $ref: "schemas/transfer.yaml#/Transfer"
    Record:
      $ref: "schemas/record.yaml#/Record"
    RecordQuery:
      $ref: "schemas/record.yaml#/RecordQuery"
    Payback:
      $ref: "schemas/payback.yaml#/Payback"
    PaybackBalanceQuery:
      $ref: "schemas/payback.yaml#/PaybackBalanceQuery"
    PaybackBalance:
      $ref: "schemas/payback.yaml#/PaybackBalance"
    PaybackAmount:
      $ref: "schemas/payback.yaml#/PaybackAmount"
    DateRange:
      $ref: "schemas/common.yaml#/DateRange"
    Error:
      $ref: "schemas/common.yaml#/Error"
  requestBodies:
    CreateCategoryRequest:
      $ref: "requestBodies/category.yaml#/CreateCategoryRequest"
    UpdateCategoryRequest:
      $ref: "requestBodies/category.yaml#/UpdateCategoryRequest"
    CreateTransactionRequest:
      $ref: "requestBodies/transaction.yaml#/CreateTransactionRequest"
    UpdateTransactionRequest:
      $ref: "requestBodies/transaction.yaml#/UpdateTransactionRequest"
    CreateSourceRequest:
      $ref: "requestBodies/source.yaml#/CreateSourceRequest"
    UpdateSourceRequest:
      $ref: "requestBodies/source.yaml#/UpdateSourceRequest"
    CreateAccountRequest:
      $ref: "requestBodies/account.yaml#/CreateAccountRequest"
    UpdateAccountRequest:
      $ref: "requestBodies/account.yaml#/UpdateAccountRequest"
    CreateAssetRequest:
      $ref: "requestBodies/asset.yaml#/CreateAssetRequest"
    UpdateAssetRequest:
      $ref: "requestBodies/asset.yaml#/UpdateAssetRequest"
    CreateTransferRequest:
      $ref: "requestBodies/transfer.yaml#/CreateTransferRequest"
    UpdateTransferRequest:
      $ref: "requestBodies/transfer.yaml#/UpdateTransferRequest"
    CreatePaybackRequest:
      $ref: "requestBodies/payback.yaml#/CreatePaybackRequest"
    UpdatePaybackRequest:
      $ref: "requestBodies/payback.yaml#/UpdatePaybackRequest"
  responses:
    CreateCategoryResponse:
      $ref: "responses/category.yaml#/CreateCategoryResponse"
    UpdateCategoryResponse:
      $ref: "responses/category.yaml#/UpdateCategoryResponse"
    GetCategoriesResponse:
      $ref: "responses/category.yaml#/GetCategoriesResponse"
    GetAmountSpentInRangeResponse:
      $ref: "responses/category.yaml#/GetAmountSpentInRangeResponse"
    CreateTransactionResponse:
      $ref: "responses/transaction.yaml#/CreateTransactionResponse"
    UpdateTransactionResponse:
      $ref: "responses/transaction.yaml#/UpdateTransactionResponse"
    CreateSourceResponse:
      $ref: "responses/source.yaml#/CreateSourceResponse"
    UpdateSourceResponse:
      $ref: "responses/source.yaml#/UpdateSourceResponse"
    GetSourcesResponse:
      $ref: "responses/source.yaml#/GetSourcesResponse"
    CreateAccountResponse:
      $ref: "responses/account.yaml#/CreateAccountResponse"
    UpdateAccountResponse:
      $ref: "responses/account.yaml#/UpdateAccountResponse"
    GetAccountsResponse:
      $ref: "responses/account.yaml#/GetAccountsResponse"
    CreateAssetResponse:
      $ref: "responses/asset.yaml#/CreateAssetResponse"
    UpdateAssetResponse:
      $ref: "responses/asset.yaml#/UpdateAssetResponse"
    GetStockValueResponse:
      $ref: "responses/asset.yaml#/GetStockValueResponse"
    GetAccountValueResponse:
      $ref: "responses/reporting.yaml#/GetAccountValueResponse"
    GetNetWorthResponse:
      $ref: "responses/reporting.yaml#/GetNetWorthResponse"
    GetTimePeriodsResponse:
      $ref: "responses/timeperiod.yaml#/GetTimePeriodsResponse"
    CreateTransferResponse:
      $ref: "responses/transfer.yaml#/CreateTransferResponse"
    UpdateTransferResponse:
      $ref: "responses/transfer.yaml#/UpdateTransferResponse"
    GetRecordsResponse:
      $ref: "responses/record.yaml#/GetRecordsResponse"
    CreatePaybackResponse:
      $ref: "responses/payback.yaml#/CreatePaybackResponse"
    UpdatePaybackResponse:
      $ref: "responses/payback.yaml#/UpdatePaybackResponse"
    GetPaybackBalanceResponse:
      $ref: "responses/payback.yaml#/GetPaybackBalanceResponse"
    GetPaybackBalanceSummaryResponse:
      $ref: "responses/payback.yaml#/GetPaybackBalanceSummaryResponse"
    Empty200:
      $ref: "responses/common.yaml#/Empty200"
    Error:
      $ref: "responses/common.yaml#/Error"
