openapi: "3.0.0"
info:
  title: "finance api"
  version: "0.0.1"
paths:
  /: {}
components:
  schemas:
    Category:
      $ref: "schemas/category.yaml#/Category"
    Budget: 
      $ref: "schemas/category.yaml#/Budget"
    AnyPeriod:
      $ref: "schemas/category.yaml#/AnyPeriod"
    SinglePeriod:
      $ref: "schemas/category.yaml#/SinglePeriod"
    RangePeriod:
      $ref: "schemas/category.yaml#/RangePeriod"
    Transaction:
      $ref: "schemas/transaction.yaml#/Transaction"
    Amount:
      $ref: "schemas/transaction.yaml#/Amount"
    TransactionQuery:
      $ref: "schemas/transaction.yaml#/TransactionQuery"
    Source:
      $ref: "schemas/source.yaml#/Source"
    SourceQuery:
      $ref: "schemas/source.yaml#/SourceQuery"
    Account:
      $ref: "schemas/account.yaml#/Account"
    Asset:
      $ref: "schemas/asset.yaml#/Asset"
    StockMetadata:
      $ref: "schemas/asset.yaml#/StockMetadata"
    AccountValue:
      $ref: "schemas/reporting.yaml#/AccountValue"
    AccountValueQuery:
      $ref: "schemas/reporting.yaml#/AccountValueQuery"
    TimePeriodRange:
      $ref: "schemas/reporting.yaml#/TimePeriodRange"
    TimePeriodCollection:
      $ref: "schemas/reporting.yaml#/TimePeriodCollection"
    TimePeriod:
      $ref: "schemas/timeperiod.yaml#/TimePeriod"
    TimePeriodQuery:
      $ref: "schemas/timeperiod.yaml#/TimePeriodQuery"
  responses:
    CreateCategoryResponse:
      $ref: "responses/category.yaml#/CreateCategoryResponse"
    UpdateCategoryResponse:
      $ref: "responses/category.yaml#/UpdateCategoryResponse"
    GetCategoriesResponse:
      $ref: "responses/category.yaml#/GetCategoriesResponse"
    CreateTransactionResponse:
      $ref: "responses/transaction.yaml#/CreateTransactionResponse"
    UpdateTransactionResponse:
      $ref: "responses/transaction.yaml#/UpdateTransactionResponse"
    GetTransactionsResponse:
      $ref: "responses/transaction.yaml#/GetTransactionsResponse"
    CreateSourceResponse:
      $ref: "responses/source.yaml#/CreateSourceResponse"
    UpdateSourceResponse:
      $ref: "responses/source.yaml#/UpdateSourceResponse"
    GetSourcesResponse:
      $ref: "responses/source.yaml#/GetSourcesResponse"
    CreateAccountResponse:
      $ref: "responses/account.yaml#/CreateAccountResponse"
    UpdateAccountResponse:
      $ref: "responses/account.yaml#/UpdateAccountResponse"
    GetAccountsResponse:
      $ref: "responses/account.yaml#/GetAccountsResponse"
    CreateAssetResponse:
      $ref: "responses/asset.yaml#/CreateAssetResponse"
    UpdateAssetResponse:
      $ref: "responses/asset.yaml#/UpdateAssetResponse"
    GetAssetsResponse:
      $ref: "responses/asset.yaml#/GetAssetsResponse"
    GetAccountValueResponse:
      $ref: "responses/reporting.yaml#/GetAccountValueResponse"
    GetNetWorthResponse:
      $ref: "responses/reporting.yaml#/GetNetWorthResponse"
    GetTimePeriodsResponse:
      $ref: "responses/timeperiod.yaml#/GetTimePeriodsResponse"
