openapi: "3.0.0"
info:
  title: "finance api"
  version: "0.0.1"
paths:
  /category:
    $ref: "paths/category.yaml#/CreateGetCategory"
  /category/{id}:
    $ref: "paths/category.yaml#/UpdateDeleteCategory"
  /transaction:
    $ref: "paths/transaction.yaml#/CreateTransaction"
  /transaction/{id}:
    $ref: "paths/transaction.yaml#/UpdateDeleteTransaction"
  /source:
    $ref: "paths/source.yaml#/CreateGetSource"
  /source/{id}:
    $ref: "paths/source.yaml#/UpdateDeleteSource"
  /account:
    $ref: "paths/account.yaml#/CreateGetAccount"
  /account/{id}:
    $ref: "paths/account.yaml#/UpdateDeleteAccount"
  /asset:
    $ref: "paths/asset.yaml#/CreateAsset"
  /asset/{id}:
    $ref: "paths/asset.yaml#/UpdateDeleteAsset"
  /reporting/accountvalue:
    $ref: "paths/reporting.yaml#/GetAccountValue"
  /reporting/networth:
    $ref: "paths/reporting.yaml#/GetNetWorth" 
  /timeperiod:
    $ref: "paths/timeperiod.yaml#/GetTimePeriod"
  /transfer:
    $ref: "paths/transfer.yaml#/CreateTransfer"
  /transfer/{id}:
    $ref: "paths/transfer.yaml#/UpdateDeleteTransfer"
  /record:
    $ref: "paths/record.yaml#/GetRecord"
components:
  schemas:
    Category:
      $ref: "schemas/category.yaml#/Category"
    Budget: 
      $ref: "schemas/category.yaml#/Budget"
    AnyPeriod:
      $ref: "schemas/category.yaml#/AnyPeriod"
    SinglePeriod:
      $ref: "schemas/category.yaml#/SinglePeriod"
    RangePeriod:
      $ref: "schemas/category.yaml#/RangePeriod"
    Transaction:
      $ref: "schemas/transaction.yaml#/Transaction"
    Amount:
      $ref: "schemas/transaction.yaml#/Amount"
    Source:
      $ref: "schemas/source.yaml#/Source"
    SourceQuery:
      $ref: "schemas/source.yaml#/SourceQuery"
    Account:
      $ref: "schemas/account.yaml#/Account"
    Asset:
      $ref: "schemas/asset.yaml#/Asset"
    StockMetadata:
      $ref: "schemas/asset.yaml#/StockMetadata"
    AccountValue:
      $ref: "schemas/reporting.yaml#/AccountValue"
    AccountValueQuery:
      $ref: "schemas/reporting.yaml#/AccountValueQuery"
    TimePeriodRange:
      $ref: "schemas/reporting.yaml#/TimePeriodRange"
    TimePeriodCollection:
      $ref: "schemas/reporting.yaml#/TimePeriodCollection"
    TimePeriod:
      $ref: "schemas/timeperiod.yaml#/TimePeriod"
    TimePeriodQuery:
      $ref: "schemas/timeperiod.yaml#/TimePeriodQuery"
    Transfer:
      $ref: "schemas/transfer.yaml#/Transfer"
    Record:
      $ref: "schemas/record.yaml#/Record"
    RecordQuery:
      $ref: "schemas/record.yaml#/RecordQuery"
  responses:
    CreateCategoryResponse:
      $ref: "responses/category.yaml#/CreateCategoryResponse"
    UpdateCategoryResponse:
      $ref: "responses/category.yaml#/UpdateCategoryResponse"
    GetCategoriesResponse:
      $ref: "responses/category.yaml#/GetCategoriesResponse"
    CreateTransactionResponse:
      $ref: "responses/transaction.yaml#/CreateTransactionResponse"
    UpdateTransactionResponse:
      $ref: "responses/transaction.yaml#/UpdateTransactionResponse"
    CreateSourceResponse:
      $ref: "responses/source.yaml#/CreateSourceResponse"
    UpdateSourceResponse:
      $ref: "responses/source.yaml#/UpdateSourceResponse"
    GetSourcesResponse:
      $ref: "responses/source.yaml#/GetSourcesResponse"
    CreateAccountResponse:
      $ref: "responses/account.yaml#/CreateAccountResponse"
    UpdateAccountResponse:
      $ref: "responses/account.yaml#/UpdateAccountResponse"
    GetAccountsResponse:
      $ref: "responses/account.yaml#/GetAccountsResponse"
    CreateAssetResponse:
      $ref: "responses/asset.yaml#/CreateAssetResponse"
    UpdateAssetResponse:
      $ref: "responses/asset.yaml#/UpdateAssetResponse"
    GetAccountValueResponse:
      $ref: "responses/reporting.yaml#/GetAccountValueResponse"
    GetNetWorthResponse:
      $ref: "responses/reporting.yaml#/GetNetWorthResponse"
    GetTimePeriodsResponse:
      $ref: "responses/timeperiod.yaml#/GetTimePeriodsResponse"
    CreateTransferResponse:
      $ref: "responses/transfer.yaml#/CreateTransferResponse"
    UpdateTransferResponse:
      $ref: "responses/transfer.yaml#/UpdateTransferResponse"
    GetRecordsResponse:
      $ref: "responses/record.yaml#/GetRecordsResponse"
    Empty200:
      $ref: "responses/common.yaml#/Empty200"
    Error:
      $ref: "responses/common.yaml#/Error"
  requestBodies:
    CreateCategoryRequest:
      $ref: "requestBodies/category.yaml#/CreateCategoryRequest"
    UpdateCategoryRequest:
      $ref: "requestBodies/category.yaml#/UpdateCategoryRequest"
    CreateTransactionRequest:
      $ref: "requestBodies/transaction.yaml#/CreateTransactionRequest"
    UpdateTransactionRequest:
      $ref: "requestBodies/transaction.yaml#/UpdateTransactionRequest"
    CreateSourceRequest:
      $ref: "requestBodies/source.yaml#/CreateSourceRequest"
    UpdateSourceRequest:
      $ref: "requestBodies/source.yaml#/UpdateSourceRequest"
    CreateAccountRequest:
      $ref: "requestBodies/account.yaml#/CreateAccountRequest"
    UpdateAccountRequest:
      $ref: "requestBodies/account.yaml#/UpdateAccountRequest"
    CreateAssetRequest:
      $ref: "requestBodies/asset.yaml#/CreateAssetRequest"
    UpdateAssetRequest:
      $ref: "requestBodies/asset.yaml#/UpdateAssetRequest"
    CreateTransferRequest:
      $ref: "requestBodies/transfer.yaml#/CreateTransferRequest"
