package com.finance.business.account

sealed trait AccountValidationError

case object AccountDoesNotExistError extends AccountValidationError
case object AccountAlreadyExistsError extends AccountValidationError
case object NameMustBeDefinedError extends AccountValidationError
case object DescriptionMustBeDefinedError extends AccountValidationError
case object NameExceedsMaxLengthError extends AccountValidationError
case object DescriptionExceedsMaxLengthError extends AccountValidationError