package com.finance.business.account

sealed trait AccountValidationError

case object AccountDoesNotExistError extends AccountValidationError
case object AccountAlreadyExistsError extends AccountValidationError